# Generated by Django 5.2.8 on 2025-11-10 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refugios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('especie', models.CharField(choices=[('F', 'Felino'), ('C', 'Canino'), ('A', 'Ave'), ('R', 'Roedor'), ('P', 'Pez'), ('O', 'Otro')], default='O', max_length=1)),
                ('descripcion', models.TextField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('adoptado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='refugios.refugio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
