# Generated by Django 5.2.8 on 2025-11-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='adoptado',
            field=models.BooleanField(),
        ),
    ]
