# Generated by Django 5.2.8 on 2025-11-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_animal_sexo_alter_animal_adoptado'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animales/'),
        ),
    ]
