# Generated by Django 5.2.8 on 2025-11-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_animal_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adoptado',
            field=models.BooleanField(default=False),
        ),
    ]
