# Generated by Django 5.2.8 on 2025-11-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_alter_animal_adoptado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
