# Generated by Django 5.2.6 on 2025-12-01 14:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0005_alter_animal_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
