# Generated by Django 5.2.8 on 2025-11-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('domicilio', models.TextField(max_length=50)),
                ('telefono', models.BigIntegerField(max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
