# Generated by Django 5.2.8 on 2025-11-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
