# Generated by Django 5.2.8 on 2025-11-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugios', '0002_alter_refugio_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='domicilio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
