# Generated by Django 5.2.8 on 2025-11-10 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoptantes', '0001_initial'),
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=20)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='adoptantes.adoptante')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animales.animal')),
            ],
        ),
    ]
