# Generated by Django 5.2.8 on 2025-11-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopcion',
            options={'ordering': ['animal']},
        ),
    ]
