# Generated by Django 5.2.8 on 2025-11-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_alter_adopcion_options'),
        ('adoptantes', '0002_adoptante_user'),
        ('animales', '0005_alter_animal_nombre'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adopcion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('adoptante',), name='unique_adoptante_pendiente'),
        ),
    ]
