# Generated by Django 5.2.8 on 2025-11-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_adopcion_unique_adoptante_pendiente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopcion',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='adopcion',
            name='unique_adoptante_pendiente',
        ),
    ]
