# Generated by Django 5.2.8 on 2025-11-25 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0004_alter_adopcion_options_and_more'),
        ('animales', '0005_alter_animal_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.animal'),
        ),
    ]
