# Generated by Django 5.2.8 on 2025-11-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptantes', '0002_adoptante_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='email',
        ),
    ]
